# Generated by Django 4.1.7 on 2023-03-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categoty_category_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='stasus',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
